config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets, only: [:index, :new, :create]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.includes(:user)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to root_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <h1 class="app-name"><a href="/">FollowApp</a></h1>
      <% if user_signed_in? %>
        <div class="user-mypage">
          <%= link_to "#{current_user.name}のマイページ", user_path(current_user), class: "btn" %>
        </div>
        <%= link_to "ログアウト", destroy_user_session_path,class: "btn", method: :delete %>
        <%= link_to  "投稿する", new_tweet_path, class: "btn" %>
      <% end %>
    </header>
      <%= yield %>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <p class = "tweet-text"><%= tweet.text %></p>
  <div class="tweet-name">
    <%= link_to  "投稿者：#{tweet.user.name}", user_path(tweet.user)%>
  </div>
</div>

app/views/tweets/index.html.erb
<div class = "tweets">
  <%= render partial: "tweet", collection: @tweets %>
</div>

app/views/tweets/new.html.erb
<div class="tweet-form">
  <%= form_with(model: @tweet, local: true) do |form| %>
    <h3>投稿する</h3>
    <div class="t-form">
      <%= form.text_area :text, class: "t-text",placeholder: "text" , rows: "10" %>
      <%= form.submit "SEND" ,class:"btn"%>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-paged">
  <div class="user-contentsd">
    <p class="user-named">ユーザー名：<%= @user.name %></p>
  </div>
</div>